name: autoreview
on: [pull_request]

jobs:
  misspellcheck:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - name: Run misspell with reviewdog
      uses: reviewdog/action-misspell@v1
      #with:
      #  pattern: "*.md"
